
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

export interface GenerationResult {
  imageUrl: string;
  styleName: string;
  description: string;
}

export const generateStyleVisualization = async (imageData: string, mode: 'Human' | 'Pet', vibe: string): Promise<GenerationResult> => {
  const base64Data = imageData.split(',')[1];
  
  // Style definitions based on vibe
  const styles: Record<string, string> = {
    bold: mode === 'Human' ? 'an edgy, textured neon-tinted wolf cut with sharp layers' : 'a bold lion-style mane trim with colorful accessories',
    classic: mode === 'Human' ? 'a sophisticated sleek chin-length bob with a precise side part' : 'a classic, tidy show-dog groom with symmetrical lines',
    natural: mode === 'Human' ? 'soft, beachy waves with natural volume and sun-kissed highlights' : 'a gentle puppy cut that follows the natural flow of the fur',
    fun: mode === 'Human' ? 'playful space buns with glitter roots and pastel highlights' : 'a quirky mohawk trim with non-toxic temporary blue tips'
  };

  const selectedStyle = styles[vibe] || styles['classic'];
  const prompt = `Style update: Apply a ${selectedStyle} to the subject in this photo. 
  It is essential to keep the facial features and original person/pet likeness identical to the source. 
  The new grooming should look like a professional salon work, integrated perfectly. 
  Photorealistic, 4k resolution.`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: {
        parts: [
          { inlineData: { mimeType: "image/jpeg", data: base64Data } },
          { text: `Grooming visualization: Take the ${mode.toLowerCase()} in this image and visualize them with ${selectedStyle}. 
Keep the subject's face, identity, and background completely the same. Seamlessly add the new grooming style. 
Professional photography, 4k, photorealistic.` }
        ]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      }
    });

    // Find the image part in the response
    let generatedBase64 = '';
    let textFeedback = '';
    
    if (response.candidates && response.candidates[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          generatedBase64 = `data:image/png;base64,${part.inlineData.data}`;
          break;
        } else if (part.text) {
          textFeedback += part.text;
        }
      }
    }

    if (!generatedBase64) {
      const refusalMessage = textFeedback ? ` Model feedback: ${textFeedback}` : "";
      throw new Error(`No image was generated by the model.${refusalMessage}`);
    }

    return {
      imageUrl: generatedBase64,
      styleName: selectedStyle.split('with')[0].trim(),
      description: `Based on your ${vibe} vibe, we've visualized this ${selectedStyle} to compliment your features.`
    };
  } catch (err: any) {
    console.error("Nano Banana Generation Error:", err);
    throw err;
  }
};
